services:
  metabase_pg:
    image: metabase/metabase:latest
    container_name: metabase_pg
    restart: unless-stopped
    ports:
      - '3030:3000'
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432  # Changé de 5434 à 5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase_password
      - MB_DB_HOST=postgresql  # Utilise le nom du service docker
      - JAVA_TIMEZONE=Europe/Paris
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    container_name: metabase_postgresql
    restart: unless-stopped
    ports:
      - '5431:5432'  # Port externe 5434, interne toujours 5432
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase_password
      - POSTGRES_DB=metabase
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql-data: